### ISSUE TITLE
Add webgl-debug

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#407]
```
jspm install webgl-debug=github:KhronosGroup/WebGLDeveloperTools -o "{main:'src/debug/webgl-debug.js'}"
```

@backspaces has managed to get this one going, we just need to include in the registry.json and add an override.

**Comment by guybedford** [comment]
@backspaces what was the update on this override? Do we still need to include this in the registry?

**Comment by backspaces** [comment]
I don't understand the question, mainly because I don't understand the way the registry works.  The github formula above works, I believe the -o is the override, right?  I just copied it from other folks.

It results in the config.js having a map: entry of:
    "webgl-debug": "github:KhronosGroup/WebGLDeveloperTools@master",
and the package.json has in overides:
      "github:KhronosGroup/WebGLDeveloperTools@master": {
        "main": "src/debug/webgl-debug.js"
      }
and in dependencies:
      "webgl-debug": "github:KhronosGroup/WebGLDeveloperTools@master"

This works in imports:
    import webglDebug from 'webgl-debug'
.. and correctly does what it's supposed to: wraps the webgl canvas context functions for debugging, both for simple debugging (error catching) and more complex debugging (writing out gl.functions with their arguments).

One downside: webgl-debug places a name in the global (window) name space, even tho it's not used due to the nifty way imports & es6 wrap the code. Is there a way to configure the package so that doesn't occur? It is legacy so no-one is surprised at this, it just is redundant and confusing.

**Comment by guybedford** [comment]
If we add this into the registry, we get the benefit of enabling `jspm install webgl-debug` for all users. That is we store the override and GitHub name in the registry and overrides here. If you look at the registry.json or package-overrides folder in this repo this should make more sense.

The global gets left in place for backwards-compatibility with existing global scripts which may expect it. We could remove it but it would make SystemJS less backwards-compatible.

My only worry with this library at this point is that because they don't tag versions on GitHub, it's always running on master meaning that it install versions are not lockable. Is there nothing on npm or elsewhere to use instead?

**Comment by backspaces** [comment]
Ah, now I get it. 

webgl-debug is a 3+ year old webgl utility which came out when webgl itself was released. 

Let me get back to the maintainer and ask for a version tag. Boy, talk about a blast from the past! Lets not put it in the registry without a version, rather than the git commit (latest commit 80658b130e).

**Comment by backspaces** [comment]
This should now work with the install in the first post, as v1.0.0.

When I now execute that jspm install, I get:
In config.js:

    "webgl-debug": "github:KhronosGroup/WebGLDeveloperTools@1.0.0",

package.json:

    "dependencies": {
      "webgl-debug": "github:KhronosGroup/WebGLDeveloperTools@^1.0.0"
    },
    "overrides": {
      "github:KhronosGroup/WebGLDeveloperTools@1.0.0": {
        "main": "src/debug/webgl-debug.js"
      }

So the version is there. It was a bit of comedy-of-errors when we did it.  Apparently version tags did not come along with my initial PR so Ken just added it by hand in GitHub.  But a clone shows the version tag. Git. Fu. ~0. Sigh. Let me know if there is any problem.

**Comment by guybedford** [comment]
Great I've added this in https://github.com/jspm/registry/commit/885d1fe2edc641dcc792c751b9d14154156c359e, should now work without the override. Just let me know if it needs any adjustments.
