### ISSUE TITLE
Public CDN path for system.0.18.3.js?

### ISSUE THREAD

**Issue by edrex** [jspm/registry#447]
I've hit a snag trying to update my project to JSPM beta.

 I'd been [using](https://github.com/edrex/hello-systemjs/blob/ca6cea5eaf288e5cbdfed9757298949dc175f539/index.html) https://jspm.io/system@0.16.7.js in my public demo (to avoid any vendoring). I'm not sure if this is a supported URL pattern or just there for internal use on the jspm.io website. Either way, the 0.18 series isn't there (maybe because it's a beta?). Is there a supported URL on the CDN for fetching system@0.18.3.js? Thanks.

**Comment by guybedford** [comment]
Unfortunately SystemJS 0.18 is not currently compatible with the jspm CDN due to removal of the versions extension. What we can do is rebuild the versions extensions into jspm's SystemJS build, but I was planning on doing this when jspm 0.16 lands as stable.

I could try and fast-track getting SystemJS updated on the CDN though if this is something that would be useful.

**Comment by peisenmann** [comment]
Is there any news on this?
