### ISSUE TITLE
jspm install -y fails if github config not configured

### ISSUE THREAD

**Issue by dannycochran** [jspm/registry#523]
When trying to run:

```
jspm install -y
```

the process would infinitely ask for my github credentials but not allow me to actually enter them. I solved this by doing:

```
jspm registry config github
```

and entering my username and then a generated token.

**Comment by guybedford** [comment]
I've pushed https://github.com/jspm/github/commit/d2c27fe1d1fcf8cc01a851185415ef401d5a9d0a so that this loop will just continue to not use credentials, and at least not loop forever just three times as it continues to hit the rate limits.

`install -y` is specifically for skipping prompts though, so don't use that option if this is no the desired behaviour.
