### ISSUE TITLE
'ionic' package not exporting globals

### ISSUE THREAD

**Issue by ackerdev** [jspm/registry#582]
I'm having trouble setting up the ionic package to properly import.

The ionic package contains two primary javascript files, `ionic.js` which defines `window.ionic`, and `ionic-angular` which depends on ionic.js and a few angular dependencies and defines nothing globally. Currently though, I cannot get `window.ionic` to be cleanly exported without explicitly importing the `ionic.js` file directly from the ionic package.

Here is my closest attempt; it _works_ but requires manually importing the `ionic.js` file:
https://github.com/ackerdev/ionic-jspm-test/blob/master/src/app.js#L1-L3
https://github.com/ackerdev/ionic-jspm-test/blob/master/package.json#L26-L54

Is it possible to configure the ionic package in such a way that I could accomplish a more appropriate import like the following?
```js
import angular from "angular"
import ionic from "ionic"
```

**Comment by guybedford** [comment]
So ionic already has an override at https://github.com/jspm/registry/blob/master/package-overrides/github/driftyco/ionic-bower%401.0.0-rc.0.json.

I copied the contents of this file into a local `override.json` file and edited the shim part to contain:

```
    "shim": {
        "js/ionic-angular": {
            "exports": "ionic",
            "deps": [
                "../css/ionic.css!",
                "./ionic",
                "angular",
                "angular-animate",
                "angular-sanitize",
                "angular-ui-router"
            ]
        }
```

I then ran `jspm install ionic -o override.json` and that then gave me back the module with the right value in the browser.

I have checked that override into the registry now with https://github.com/jspm/registry/commit/e4c873798bf4b41354d1c763172f7715fbb99d0e so that this should be working for you. Let me know if you need help further here.

**Comment by ackerdev** [comment]
Well. Um... Huh. It works.

I am sure that I had tried to do exactly this in a local override, amongst several other things, in an attempt to get this to work. I felt like some of my overrides didn't change anything at times... Are registry overrides still used even when a local override is in package.json? Is there some caveat here that I'm not aware of?

**Comment by guybedford** [comment]
Glad to hear it is working. Yes, local overrides will merge with the registry overrides when being used.

**Comment by vadimpopa** [comment]
Before trying to work on override, anyone has tried to make one for Ionic2 too ?: http://ionicframework.com/docs/v2/getting-started/installation/
