### ISSUE TITLE
Help with installing npm:angular-bootstrap-datetimepicker

### ISSUE THREAD

**Issue by Successful** [jspm/registry#803]
I haven't got the hang of this yet, trying to install npm:angular-bootstrap-datetimepicker that has dependencies on some files.

This is my current override, but i think i use the deps array wrong.

```
"npm:angular-bootstrap-datetimepicker@1.0.1": {
        "main": "js/datetimepicker",
        "directories": {
          "lib": "src"
        },
        "shim": {
          "js/datetimepicker": {
            "deps": [
              "jquery",
              "angular",
              "moment",
              "js/datetimepicker.templates.js",
              "templates/datetimepicker.html",
              "css/datetimepicker.css"
            ]
          }
        }
      }
```

![image](https://cloud.githubusercontent.com/assets/5755790/13576491/40a3d582-e48e-11e5-92d2-97f9311890f0.png)

**Comment by guybedford** [comment]
Shim deps are relative as if you had written them as `require('...')` deps int he file itself. So instead of `templates/datetimepicker.html` you probably want `../templates/datetimepicker.html`. Note though that loading HTML will be treated as a JS file so you probably want this to be a plugin load I guess.
