### ISSUE TITLE
angular-bootstrap is wrong

### ISSUE THREAD

**Issue by npbenjohnson** [jspm/registry#879]
From https://github.com/angular-ui/bootstrap-bower/pull/61 "You have to use angular-ui-bootstrap not angular-bootstrap" which is npm:angular-ui-bootstrap the current one requires an angular global shim and cjs format override

**Comment by guybedford** [comment]
There was an override for https://github.com/jspm/registry/blob/master/package-overrides/github/angular-ui/bootstrap-bower%400.12.0.json, perhaps that override can just be copied to the latest 1.0.0 version?

**Comment by npbenjohnson** [comment]
Is there a reason to use bootstrap-bower? It only needs an override because it is separately maintained for bower. https://github.com/angular-ui/bootstrap#install-with-npm (the bower info is also right below this link)

**Comment by guybedford** [comment]
For Angular 1 the convention we have is to use the github repos as it avoids downloading unnecessary npm dependencies. Picking overrides is very much about balancing which is the best in each case, but as long as there aren't unnecessary dependencies, and the dependencies used are the ones already in use (eg angular as a dependency should always be `github:angular/bower-angular` due to https://github.com/jspm/registry/blob/master/registry.json#L31), then the override will be accepted here fine.
